"""add scan jobs queue and scan duration

Revision ID: 268eec145533
Revises: 7d7585afd230
Create Date: 2026-08-14 18:07:41.944957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268eec145533'
down_revision: Union[str, Sequence[str], None] = '7d7585afd230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('scan_number', sa.Integer(), nullable=False),
    sa.Column('segment_start_seconds', sa.Integer(), nullable=False),
    sa.Column('segment_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('eligible_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance.sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'scan_number', name='uq_scan_job_session_scan'),
    schema='attendance'
    )
    op.create_index('ix_scan_jobs_status_priority_eligible', 'scan_jobs', ['status', 'priority', 'eligible_at'], unique=False, schema='attendance')
    op.add_column('system_settings', sa.Column('scan_duration_seconds', sa.Integer(), server_default='120', nullable=False), schema='attendance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'scan_duration_seconds', schema='attendance')
    op.drop_index('ix_scan_jobs_status_priority_eligible', table_name='scan_jobs', schema='attendance')
    op.drop_table('scan_jobs', schema='attendance')
    # ### end Alembic commands ###
