"""add scan number to attendance logs

Revision ID: 7d7585afd230
Revises: 51b599b1c832
Create Date: 2026-08-14 00:55:19.640510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7585afd230'
down_revision: Union[str, Sequence[str], None] = '51b599b1c832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_logs', sa.Column('scan_number', sa.Integer(), nullable=False), schema='attendance')
    op.add_column('attendance_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='attendance')
    op.create_unique_constraint('uq_attendance_log_session_student_scan', 'attendance_logs', ['session_id', 'student_id', 'scan_number'], schema='attendance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attendance_log_session_student_scan', 'attendance_logs', schema='attendance', type_='unique')
    op.drop_column('attendance_logs', 'created_at', schema='attendance')
    op.drop_column('attendance_logs', 'scan_number', schema='attendance')
    # ### end Alembic commands ###
